AllCops:
  # 自動生成ファイル除外
  Exclude:
    - 'db/schema.rb'
  DisplayCopName: true

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

MixinUsage:
  Include:
    - app/**/*.rb
