version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/labosa
      - public-data:/labosa/public
      - tmp-data:/labosa/tmp
      - log-data:/labosa/log
      - bundle_install:/usr/local/bundle
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/postgres
    environment:
      POSTGRES_USER: mantis
      POSTGRES_PASSWORD: mantis
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/labosa/public
      - tmp-data:/labosa/tmp
    ports:
      - 8080:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  bundle_install:
